spring:
  #数据库
  datasource:
    #地址
    url: jdbc:mysql://192.168.0.112:3306/ssm-vue-frame?useUnicode=true&characterEncoding=utf8&useSSL=false
    #用户名
    username: root
    #密码
    password: root
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    suffix: .html
#服务器
server:
  #端口号
  port: 8080
  #访问根路径
  servlet:
    context-path: /ssm-vue-frame
#日志
logging:
  file: D:/log/my_log.log
  level:
    com: DEBUG
#公众号配置
officialaccounts:
  #用于换取accessToken的url
  getAccessTokenBaseUrl: https://api.weixin.qq.com/sns/oauth2/access_token
  #用于拉取用户信息的url
  getUserInfoBaseUrl: https://api.weixin.qq.com/sns/userinfo
  appID: wx395af6944120afc3
  appsecret: 42810b3fcc2dc044b569374b7f10d8a6